// <auto-generated />
namespace CSEmployerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _6thInitialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6thInitialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201312041811423_6thInitialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
