// <auto-generated />
namespace CSEmployerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _3rdInitialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rdInitialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201311080013406_3rdInitialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
