// <auto-generated />
namespace CSEmployerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _21stintilization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21stintilization));
        
        string IMigrationMetadata.Id
        {
            get { return "201403112316164_21stintilization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
