// <auto-generated />
namespace CSEmployerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _22ndintilization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22ndintilization));
        
        string IMigrationMetadata.Id
        {
            get { return "201404101839430_22ndintilization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
