// <auto-generated />
namespace CSEmployerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _19thInitialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19thInitialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201403040002064_19thInitialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
