// <auto-generated />
namespace CSEmployerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _10thInitialze : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10thInitialze));
        
        string IMigrationMetadata.Id
        {
            get { return "201401240032474_10thInitialze"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
