// <auto-generated />
namespace CSEmployerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMajorColumntoApplicant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMajorColumntoApplicant));
        
        string IMigrationMetadata.Id
        {
            get { return "201409100235158_AddMajorColumntoApplicant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
